trigger:
  - master
variables:
  - name: msvc.version
    value: 14.1
  - name: win.boostDir
    value: C:\hostedtoolcache\windows\Boost
  - group: Common
jobs:
  - job: Linux
    pool:
        vmImage: ubuntu-18.04
    workspace:
        clean: all
    steps:
      - script: |
            sudo apt-get update
            sudo apt-get -y install libboost-all-dev
            curl -L https://github.com/ispc/ispc/releases/download/v$(ispc.version)/ispc-v$(ispc.version)-linux.tar.gz -o ispc.tar.gz
            tar xzf ispc.tar.gz
        displayName: Download dependencies
      - script: >
            $(Build.SourcesDirectory)/build.sh \
                -DCUTTLEFISH_ISPC_PATH=$(Build.SourcesDirectory)/ispc-v$(ispc.version)-linux/bin/ispc \
                -o DeepSea-tools-linux.tar.gz
        workingDirectory: $(Build.BinariesDirectory)
        displayName: Build
      - publish: $(Build.BinariesDirectory)/DeepSea-tools-linux.tar.gz
        artifact: Linux
        displayName: Publish
  - job: Mac
    pool:
        vmImage: macOS-latest
    workspace:
        clean: all
    steps:
      - script: |
            curl -L https://github.com/ispc/ispc/releases/download/v$(ispc.version)/ispc-v$(ispc.version)-macOS.tar.gz -o ispc.tar.gz
            tar xzf ispc.tar.gz
        displayName: Download ISPC
        workingDirectory: $(Build.SourcesDirectory)
      - script: |
            git clone https://github.com/boostorg/boost.git -b boost-$(boost.version)
            cd boost
            git submodule update --init
        displayName: Download boost
        workingDirectory: $(Build.SourcesDirectory)
      - task: CMake@1
        inputs:
            workingDirectory: $(Build.BinariesDirectory)/boost-build
            cmakeArgs: >-
                -DCMAKE_BUILD_TYPE=Release -DCMAKE_OSX_ARCHITECTURES="arm64;x86_64"
                -DCMAKE_OSX_DEPLOYMENT_TARGET=10.14
                -DCMAKE_INSTALL_PREFIX=$(Build.BinariesDirectory)/boost
                -DBOOST_EXCLUDE_LIBRARIES="context;coroutine;fiber;asio;log"
                $(Build.SourcesDirectory)/boost
        displayName: Run CMake boost
      - task: CMake@1
        inputs:
            workingDirectory: $(Build.BinariesDirectory)/boost-build
            cmakeArgs: --build . -j $(cores.count)
        displayName: Build boost
      - task: CMake@1
        inputs:
            workingDirectory: $(Build.BinariesDirectory)/boost-build
            cmakeArgs: --build . --target install
        displayName: Install boost
      - script: |
            $(Build.SourcesDirectory)/build.sh -GXcode \
                -DCUTTLEFISH_ISPC_PATH="$(Build.SourcesDirectory)/ispc-v$(ispc.version)-macOS/bin/ispc" \
                -DCMAKE_OSX_ARCHITECTURES="arm64;x86_64" \
                -DCMAKE_OSX_DEPLOYMENT_TARGET=10.14 \
                -DCMAKE_PREFIX_PATH="$(Build.BinariesDirectory)/boost" \
                -DCMAKE_BUILD_WITH_INSTALL_RPATH=ON -o DeepSea-tools-mac.tar.gz
        workingDirectory: $(Build.BinariesDirectory)
        displayName: Build
      - publish: $(Build.BinariesDirectory)/DeepSea-tools-mac.tar.gz
        artifact: Mac
        displayName: Publish
  - job: Windows
    pool:
        vmImage: windows-latest
    workspace:
        clean: all
    steps:
      - bash: |
            curl -L https://github.com/ispc/ispc/releases/download/v$(ispc.version)/ispc-v$(ispc.version)-windows.zip -o ispc.zip
            unzip ispc.zip
        displayName: Download ISPC
        workingDirectory: $(Build.SourcesDirectory)
      - powershell: |
            $underscoreVersion = "$(boost.version)".replace(".", "_")
            $url = "https://sourceforge.net/projects/boost/files/boost-binaries/$(boost.version)/boost_$underscoreVersion-msvc-$(msvc.version)-32.exe"
            (New-Object System.Net.WebClient).DownloadFile($url, "$env:TEMP\boost.exe")
            Start-Process -Wait -FilePath "$env:TEMP\boost.exe" "/SILENT","/SP-","/SUPPRESSMSGBOXES","/DIR=$(win.boostDir)"
        displayName: Download boost
      - script: |
            $(Build.SourcesDirectory)\build.bat -A Win32 -T v141 "-DBOOST_ROOT^=$(win.boostDir)" ^
                "-DCUTTLEFISH_ISPC_PATH^=$(Build.SourcesDirectory)/ispc-v$(ispc.version)-windows/bin/ispc.exe" ^
                -o DeepSea-tools-win32.zip
        workingDirectory: $(Build.BinariesDirectory)
        displayName: Build
      - publish: $(Build.BinariesDirectory)\DeepSea-tools-win32.zip
        artifact: Windows
        displayName: Publish

# vim: ts=4 sts=4 sw=4 et
