trigger:
  - master
variables:
  - name: ispc.version
    value: 1.16.1
  - name: msvc.version
    value: 14.0
  - name: win.boostDir
    value: C:\hostedtoolcache\windows\Boost
  - group: Common
jobs:
  - job: Linux
    pool:
        vmImage: ubuntu-18.04
    workspace:
        clean: all
    steps:
      - script: |
            sudo apt-get update
            sudo apt-get -y install libboost-all-dev
            curl -L https://github.com/ispc/ispc/releases/download/v$(ispc.version)/ispc-v$(ispc.version)-linux.tar.gz -o ispc.tar.gz
            tar xzf ispc.tar.gz
        displayName: Download dependencies
      - script: >
            $(Build.SourcesDirectory)/build.sh \
                -DCUTTLEFISH_ISPC_PATH=$(Build.SourcesDirectory)/ispc-v$(ispc.version)-linux/bin/ispc \
                -o DeepSea-tools-linux.tar.gz
        workingDirectory: $(Build.BinariesDirectory)
        displayName: Build
      - publish: $(Build.BinariesDirectory)/DeepSea-tools-linux.tar.gz
        artifact: Linux
        displayName: Publish
  - job: Mac_x86_64
    pool:
        vmImage: macOS-latest
    workspace:
        clean: all
    steps:
      - script: brew install boost ispc
        displayName: Download dependencies
      - script: |
            $(Build.SourcesDirectory)/build.sh -o DeepSea-tools-mac.tar.gz
        workingDirectory: $(Build.BinariesDirectory)
        displayName: Build
      - publish: $(Build.BinariesDirectory)/DeepSea-tools-mac.tar.gz
        artifact: Mac-x86-64
        displayName: Publish
#  - job: Mac_arm64
#    pool:
#        vmImage: macOS-latest
#    workspace:
#        clean: all
#    steps:
#      - script: brew install boost ispc
#        displayName: Download dependencies
#      - script: |
#            $(Build.SourcesDirectory)/build.sh -DCMAKE_OSX_ARCHITECTURES=arm64 \
#                -o DeepSea-tools-mac-arm64.tar.gz
#        workingDirectory: $(Build.BinariesDirectory)
#        displayName: Build
#      - publish: $(Build.BinariesDirectory)/DeepSea-tools-mac-arm64.tar.gz
#        artifact: Mac-arm64
#        displayName: Publish
  - job: Windows
    pool:
        vmImage: windows-2019
    workspace:
        clean: all
    steps:
      - bash: |
            curl -L https://github.com/ispc/ispc/releases/download/v$(ispc.version)/ispc-v$(ispc.version)-windows.zip -o ispc.zip
            unzip ispc.zip
        displayName: Download ISPC
        workingDirectory: $(Build.SourcesDirectory)
      - powershell: |
            $underscoreVersion = "$(boost.version)".replace(".", "_")
            $url = "https://sourceforge.net/projects/boost/files/boost-binaries/$(boost.version)/boost_$underscoreVersion-msvc-$(msvc.version)-32.exe"
            (New-Object System.Net.WebClient).DownloadFile($url, "$env:TEMP\boost.exe")
            Start-Process -Wait -FilePath "$env:TEMP\boost.exe" "/SILENT","/SP-","/SUPPRESSMSGBOXES","/DIR=$(win.boostDir)"
        displayName: Download boost
      - script: |
            $(Build.SourcesDirectory)\build.bat -A Win32 -T v140 "-DBOOST_ROOT^=$(win.boostDir)" ^
                "-DCUTTLEFISH_ISPC_PATH^=$(Build.SourcesDirectory)/ispc-v$(ispc.version)-windows/bin/ispc.exe" ^
                -o DeepSea-tools-win32.zip
        workingDirectory: $(Build.BinariesDirectory)
        displayName: Build
      - publish: $(Build.BinariesDirectory)\DeepSea-tools-win32.zip
        artifact: Windows
        displayName: Publish

# vim: ts=4 sts=4 sw=4 et
